services:
  - type: web
    name: medinsight-rag-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python ingest.py
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
